-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.employees
(
    id uuid NOT NULL,
    updated_at timestamp with time zone,
    name text COLLATE pg_catalog."default",
    age integer,
    CONSTRAINT employees_pkey PRIMARY KEY (id),
    CONSTRAINT employees_id_fkey FOREIGN KEY (id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.employees
    OWNER to postgres;

ALTER TABLE IF EXISTS public.employees
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.employees TO anon;

GRANT ALL ON TABLE public.employees TO authenticated;

GRANT ALL ON TABLE public.employees TO postgres;

GRANT ALL ON TABLE public.employees TO service_role;
CREATE POLICY "パブリックなプロフィールはだれでも参照（sel"
    ON public.employees
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);
CREATE POLICY "自身のプロフィールを更新（update）できる。"
    ON public.employees
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING ((auth.uid() = id));
CREATE POLICY "自身のプロフィールを追加（insert）できる。"
    ON public.employees
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK ((auth.uid() = id));

CREATE TABLE IF NOT EXISTS public.companies
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    CONSTRAINT companies_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.companies
    OWNER to postgres;

GRANT ALL ON TABLE public.companies TO anon;

GRANT ALL ON TABLE public.companies TO authenticated;

GRANT ALL ON TABLE public.companies TO postgres;

GRANT ALL ON TABLE public.companies TO service_role;
